export const stat_data = [
  {
    name: 'Buy Call',
    view: 'Bullish',
    data: [
      {
        id: 1,
        pid: 1,
        view: 'Bullish',
        name: 'Buy Call',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Sell Put',
    view: 'Bullish',
    data: [
      {
        id: 2,
        pid: 2,
        view: 'Bullish',
        name: 'Sell Put',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Bull Call Spread',
    view: 'Bullish',
    data: [
      {
        id: 3,
        pid: 3,
        view: 'Bullish',
        name: 'Bull Call Spread',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 4,
        pid: 3,
        view: 'Bullish',
        name: 'Bull Call Spread',
        buy_sell: 'S',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
    ],
  },
  {
    name: 'Bull Put Spread',
    view: 'Bullish',
    data: [
      {
        id: 5,
        pid: 5,
        view: 'Bullish',
        name: 'Bull Put Spread',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 6,
        pid: 5,
        view: 'Bullish',
        name: 'Bull Put Spread',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
    ],
  },
  {
    name: 'Call Ratio Back Spread',
    view: 'Bullish',
    data: [
      {
        id: 7,
        pid: 7,
        view: 'Bullish',
        name: 'Call Ratio Back Spread',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 8,
        pid: 7,
        view: 'Bullish',
        name: 'Call Ratio Back Spread',
        buy_sell: 'B',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 2,
        natural: '22-Feb',
        diff: 200,
      },
    ],
  },
  {
    name: 'Long Calander With Calls',
    view: 'Bullish',
    data: [
      {
        id: 9,
        pid: 9,
        view: 'Bullish',
        name: 'Long Calander With Calls',
        buy_sell: 'S',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
      {
        id: 10,
        pid: 9,
        view: 'Bullish',
        name: 'Long Calander With Calls',
        buy_sell: 'B',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 392,
        lot: 1,
        natural: '28-March',
        diff: 200,
      },
    ],
  },
  {
    name: 'Bull Condore',
    view: 'Bullish',
    data: [
      {
        id: 11,
        pid: 11,
        view: 'Bullish',
        name: 'Bull Condore',
        buy_sell: 'B',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 12,
        pid: 11,
        view: 'Bullish',
        name: 'Bull Condore',
        buy_sell: 'S',
        strike_price: 22650,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 450,
      },
      {
        id: 13,
        pid: 11,
        view: 'Bullish',
        name: 'Bull Condore',
        buy_sell: 'S',
        strike_price: 22850,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 650,
      },
      {
        id: 14,
        pid: 11,
        view: 'Bullish',
        name: 'Bull Condore',
        buy_sell: 'B',
        strike_price: 23050,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 850,
      },
    ],
  },
  {
    name: 'Bull Butterfly',
    view: 'Bullish',
    data: [
      {
        id: 15,
        pid: 15,
        view: 'Bullish',
        name: 'Bull Butterfly',
        buy_sell: 'B',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 16,
        pid: 15,
        view: 'Bullish',
        name: 'Bull Butterfly',
        buy_sell: 'S',
        strike_price: 22650,
        ce_pe: 'CE',
        price: 0.05,
        lot: 2,
        natural: '22-Feb',
        diff: 450,
      },
      {
        id: 17,
        pid: 15,
        view: 'Bullish',
        name: 'Bull Butterfly',
        buy_sell: 'B',
        strike_price: 22850,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 650,
      },
    ],
  },
  {
    name: 'Range Forward',
    view: 'Bullish',
    data: [
      {
        id: 18,
        pid: 18,
        view: 'Bullish',
        name: 'Range Forward',
        buy_sell: 'B',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 19,
        pid: 18,
        view: 'Bullish',
        name: 'Range Forward',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
    ],
  },
  {
    name: 'Long Synthetic Forward',
    view: 'Bullish',
    data: [
      {
        id: 20,
        pid: 20,
        view: 'Bullish',
        name: 'Long Synthetic Forward',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 21,
        pid: 20,
        view: 'Bullish',
        name: 'Long Synthetic Forward',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Buy Put',
    view: 'Bearish',
    data: [
      {
        id: 22,
        pid: 22,
        view: 'Bearish',
        name: 'Buy Put',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Sell Call',
    view: 'Bearish',
    data: [
      {
        id: 23,
        pid: 23,
        view: 'Bearish',
        name: 'Sell Call',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Bear Call Spread',
    view: 'Bearish',
    data: [
      {
        id: 24,
        pid: 24,
        view: 'Bearish',
        name: 'Bear Call Spread',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 25,
        pid: 24,
        view: 'Bearish',
        name: 'Bear Call Spread',
        buy_sell: 'B',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
    ],
  },
  {
    name: 'Bear Put Spread',
    view: 'Bearish',
    data: [
      {
        id: 26,
        pid: 26,
        view: 'Bearish',
        name: 'Bear Put Spread',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 27,
        pid: 26,
        view: 'Bearish',
        name: 'Bear Put Spread',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
    ],
  },
  {
    name: 'Put Ratio Back Spread',
    view: 'Bearish',
    data: [
      {
        id: 28,
        pid: 28,
        view: 'Bearish',
        name: 'Put Ratio Back Spread',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 29,
        pid: 28,
        view: 'Bearish',
        name: 'Put Ratio Back Spread',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 2,
        natural: '22-Feb',
        diff: -200,
      },
    ],
  },
  {
    name: 'Long Calendar with Puts',
    view: 'Bearish',
    data: [
      {
        id: 30,
        pid: 30,
        view: 'Bearish',
        name: 'Long Calendar with Puts',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 31,
        pid: 30,
        view: 'Bearish',
        name: 'Long Calendar with Puts',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 222,
        lot: 1,
        natural: '28-March',
        diff: -200,
      },
    ],
  },
  {
    name: 'Bear Condor',
    view: 'Bearish',
    data: [
      {
        id: 32,
        pid: 32,
        view: 'Bearish',
        name: 'Bear Condor',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 33,
        pid: 32,
        view: 'Bearish',
        name: 'Bear Condor',
        buy_sell: 'S',
        strike_price: 21800,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -400,
      },
      {
        id: 34,
        pid: 32,
        view: 'Bearish',
        name: 'Bear Condor',
        buy_sell: 'S',
        strike_price: 21600,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -600,
      },
      {
        id: 35,
        pid: 32,
        view: 'Bearish',
        name: 'Bear Condor',
        buy_sell: 'B',
        strike_price: 21400,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -800,
      },
    ],
  },
  {
    name: 'Bear Butterfly',
    view: 'Bearish',
    data: [
      {
        id: 36,
        pid: 36,
        view: 'Bearish',
        name: 'Bear Butterfly',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 37,
        pid: 36,
        view: 'Bearish',
        name: 'Bear Butterfly',
        buy_sell: 'S',
        strike_price: 21800,
        ce_pe: 'PE',
        price: 0.05,
        lot: 2,
        natural: '22-Feb',
        diff: -400,
      },
      {
        id: 38,
        pid: 36,
        view: 'Bearish',
        name: 'Bear Butterfly',
        buy_sell: 'B',
        strike_price: 21600,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -600,
      },
    ],
  },
  {
    name: 'Risk Reversal',
    view: 'Bearish',
    data: [
      {
        id: 39,
        pid: 39,
        view: 'Bearish',
        name: 'Risk Reversal',
        buy_sell: 'S',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 40,
        pid: 39,
        view: 'Bearish',
        name: 'Risk Reversal',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
    ],
  },
  {
    name: 'Short Synthetic Future',
    view: 'Bearish',
    data: [
      {
        id: 41,
        pid: 41,
        view: 'Bearish',
        name: 'Short Synthetic Future',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 42,
        pid: 41,
        view: 'Bearish',
        name: 'Short Synthetic Future',
        buy_sell: 'B',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Short Straddle',
    view: 'Natural',
    data: [
      {
        id: 43,
        pid: 43,
        view: 'Natural',
        name: 'Short Straddle',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 44,
        pid: 43,
        view: 'Natural',
        name: 'Short Straddle',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
    ],
  },
  {
    name: 'Iron Butterfly',
    view: 'Natural',
    data: [
      {
        id: 45,
        pid: 45,
        view: 'Natural',
        name: 'Iron Butterfly',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 46,
        pid: 45,
        view: 'Natural',
        name: 'Iron Butterfly',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 47,
        pid: 45,
        view: 'Natural',
        name: 'Iron Butterfly',
        buy_sell: 'S',
        strike_price: 22200,
        ce_pe: 'CE',
        price: 17.65,
        lot: 1,
        natural: '22-Feb',
        diff: 0,
      },
      {
        id: 48,
        pid: 45,
        view: 'Natural',
        name: 'Iron Butterfly',
        buy_sell: 'B',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
    ],
  },
  {
    name: 'Short Strangle',
    view: 'Natural',
    data: [
      {
        id: 49,
        pid: 49,
        view: 'Natural',
        name: 'Short Strangle',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 50,
        pid: 49,
        view: 'Natural',
        name: 'Short Strangle',
        buy_sell: 'S',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
    ],
  },
  {
    name: 'Short Iron Condor',
    view: 'Natural',
    data: [
      {
        id: 51,
        pid: 51,
        view: 'Natural',
        name: 'Short Iron Condor',
        buy_sell: 'B',
        strike_price: 21800,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -400,
      },
      {
        id: 52,
        pid: 51,
        view: 'Natural',
        name: 'Short Iron Condor',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 53,
        pid: 51,
        view: 'Natural',
        name: 'Short Iron Condor',
        buy_sell: 'S',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
      {
        id: 54,
        pid: 51,
        view: 'Natural',
        name: 'Short Iron Condor',
        buy_sell: 'B',
        strike_price: 22600,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 400,
      },
    ],
  },
  {
    name: 'Batman',
    view: 'Natural',
    data: [
      {
        id: 55,
        pid: 55,
        view: 'Natural',
        name: 'Batman',
        buy_sell: 'B',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
      {
        id: 56,
        pid: 55,
        view: 'Natural',
        name: 'Batman',
        buy_sell: 'S',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 57,
        pid: 55,
        view: 'Natural',
        name: 'Batman',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 58,
        pid: 55,
        view: 'Natural',
        name: 'Batman',
        buy_sell: 'S',
        strike_price: 21950,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -250,
      },
    ],
  },
  {
    name: 'Double Plateau',
    view: 'Natural',
    data: [
      {
        id: 59,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'B',
        strike_price: 22450,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 250,
      },
      {
        id: 60,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'S',
        strike_price: 22650,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 450,
      },
      {
        id: 61,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'S',
        strike_price: 22850,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 650,
      },
      {
        id: 62,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'B',
        strike_price: 23050,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 850,
      },
      {
        id: 63,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'B',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 64,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'S',
        strike_price: 21800,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -400,
      },
      {
        id: 65,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'S',
        strike_price: 21600,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -600,
      },
      {
        id: 66,
        pid: 59,
        view: 'Natural',
        name: 'Double Plateau',
        buy_sell: 'B',
        strike_price: 21400,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -800,
      },
    ],
  },
  {
    name: 'Jade Lizard',
    view: 'Natural',
    data: [
      {
        id: 67,
        pid: 67,
        view: 'Natural',
        name: 'Jade Lizard',
        buy_sell: 'S',
        strike_price: 22000,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -200,
      },
      {
        id: 68,
        pid: 67,
        view: 'Natural',
        name: 'Jade Lizard',
        buy_sell: 'S',
        strike_price: 22700,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 500,
      },
      {
        id: 69,
        pid: 67,
        view: 'Natural',
        name: 'Jade Lizard',
        buy_sell: 'B',
        strike_price: 22850,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 650,
      },
    ],
  },
  {
    name: 'Reverse Jade Lizard',
    view: 'Natural',
    data: [
      {
        id: 70,
        pid: 70,
        view: 'Natural',
        name: 'Reverse Jade Lizard',
        buy_sell: 'S',
        strike_price: 22400,
        ce_pe: 'CE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: 200,
      },
      {
        id: 71,
        pid: 70,
        view: 'Natural',
        name: 'Reverse Jade Lizard',
        buy_sell: 'S',
        strike_price: 21800,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -400,
      },
      {
        id: 72,
        pid: 70,
        view: 'Natural',
        name: 'Reverse Jade Lizard',
        buy_sell: 'B',
        strike_price: 21650,
        ce_pe: 'PE',
        price: 0.05,
        lot: 1,
        natural: '22-Feb',
        diff: -550,
      },
    ],
  },
];
